### ISSUE TITLE
Tengo un issue

### ISSUE THREAD

**Issue by brujua** [agrup/PAW#2]
Che tengo un Issue con el proyecto, mas puntualmente con su equipo de trabajo.
El problema es el nivel de pateticidad de los integrantes. Fijense si pueden hacer algo al respecto.
Saludos.

**Comment by agrup** [comment]
hola buen día, la verdad no entiendo que queres decir , hasta luego muchas gracias

**Comment by woini2727** [comment]
Hola brujua gracias por las observaciones, estamos haciendo todo lo que esta a nuestro alcance para mejorar el equipo de trabajo. Mientras tanto puede lamernos el escroto.

Salu2.
PAW team

**Comment by agrup** [comment]
siscate siscate 
firma el siscador
